### ISSUE TITLE
xCon - Still cannot be detected with this , kindly help

### ISSUE THREAD

**Issue by vickydhas** [masbog/isJB#1]
Hello Developer, 

I have a phone with jailbroken device installed and done via xCon application service.

the source code IPA compiled and installed on that device still shows that the phone is not JB. 

Can help on this please.

![error1](https://cloud.githubusercontent.com/assets/834663/23941243/0ecd6506-09a3-11e7-92a3-f6519d7a50b7.jpeg)
![error2](https://cloud.githubusercontent.com/assets/834663/23941250/149d77be-09a3-11e7-8263-85c55ec75a2c.jpeg)

**Comment by masbog** [comment]
try as your custom, change the method isJB with your unique name... heheheh, may i know which version did you install of xCon?

**Comment by vickydhas** [comment]
The xCon version is 41, I am afraid i did not get the line understood 'change the method isJB with your unique name'.

**Comment by masbog** [comment]
change this "BOOL isJB();" in your project, which source xcone from cydia repo dude?

**Comment by masbog** [comment]
![image](https://cloud.githubusercontent.com/assets/663374/23996825/7b972d00-0a81-11e7-9fd1-e9e04cd68648.png)
![screen shot 2017-03-16 at 7 48 51 pm](https://cloud.githubusercontent.com/assets/663374/23996847/9a4b244a-0a81-11e7-9098-baab835ccf71.png)
![screen shot 2017-03-16 at 7 48 45 pm](https://cloud.githubusercontent.com/assets/663374/23996848/9a4b6874-0a81-11e7-8dc8-3f09998fef6c.png)

did you used latest code?

**Comment by vickydhas** [comment]
I'll try and update you my friend
-- 
Sent from my iPhone6+

**Comment by masbog** [comment]
@vickydhas thank you... keep update for the best here... (y) 👍

**Comment by masbog** [comment]
@vickydhas be careful installed xCon will be make PayPal apps not run... 😞

**Comment by vickydhas** [comment]
Its my colleagues device that already have installed with JB  phone , I am
trying to build our app such that if its detects JB device should not allow
to proceed.



Thanks,

Regards,
Vicky S Dhas
Contact: +65 9183 9203
Email :vickydhas@gmail.com/vickydhas@yahoo.co.in

**Comment by masbog** [comment]
@vickydhas yes, for finance apps i recommendation to all my client didn't allow run on jailbroken device, because it will dangerous, but it possible to patch by reverse engineering,,, keep your application check hash of it and obfuscate the hash if stored local... and update regularly... 🤗

**Comment by vickydhas** [comment]
Hello Masbog,

I have tried it but haven't got success.

As you have mentioned to change the BOO isJB(); function , I already see in your code that there is an entry for XCon detection. Still For the Jailbroken Device having Xcon it is not recognized as JB.

>         || [[NSFileManager defaultManager] fileExistsAtPath:[NSString stringWithFormat:@"/%@%@%@%@%@%@%@", @"Library/MobileS", @"ubstrate/Dy",@"nami", @"cLi", @"braries/", @" xCon.", @"dylib"]]

Secondly what you mentioned about Hash changing, I am afraid I am bit noob on that part, can advice me what exactly needs to be done. 

Thanks for helping out in this.

**Comment by masbog** [comment]
Hi, sorry for late response, about hashing maybe this article can explain about it... https://applidium.com/en/news/securing_ios_apps_patching_binaries/
"An attack at the binary level is difficult to counter."

**Comment by vickydhas** [comment]
Thanks my friend, we were unable to still bypass xCon still so we kept this as exceptional case. Hope we get some insights on this. I can close this issue still.

**Comment by masbog** [comment]
hi i was update my code, i found root cause of your problem :)

**Comment by vickydhas** [comment]
Thanks for help 🙂
-- 
Sent from my iPhone6+
