### ISSUE TITLE
Is there a problem if I make a tweak to bypass this? XD

### ISSUE THREAD

**Issue by jakeajames** [masbog/isJB#2]
Thanks for giving ideas, now I know what I need to bypass to make a good bypass for every jailbreak detection. Bye bye 👋

**Comment by masbog** [comment]
haha no problem dude, just show your tweak XD and i will update this source... haha 👍

**Comment by jakeajames** [comment]
updated xCon and now it doesn't detect anymore, lol

strange because xCon doesn't blacklist Cydia.app

**Comment by masbog** [comment]
Check my latest code WKWK
